config/routes.rb
Rails.application.routes.draw do
  resources :guesses
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guess.rb
class Guess < ApplicationRecord
    /Para la asociacion de People y guesses/
    has_and_belongs_to_many :people

end

app/models/person.rb
class Person < ApplicationRecord
    /Para la asociacion de People y guesses/
    has_and_belongs_to_many :guesses

    /Para disponer del formulario de guess en people/
    accepts_nested_attributes_for :guesses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  before_action :set_guess, only: %i[ show edit update destroy ]

  # GET /guesses or /guesses.json
  def index
    @guesses = Guess.all
  end

  # GET /guesses/1 or /guesses/1.json
  def show
  end

  # GET /guesses/new
  def new
    @guess = Guess.new
  end

  # GET /guesses/1/edit
  def edit
  end

  # POST /guesses or /guesses.json
  def create
    @guess = Guess.new(guess_params)

    respond_to do |format|
      if @guess.save
        format.html { redirect_to @guess, notice: "Guess was successfully created." }
        format.json { render :show, status: :created, location: @guess }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guess.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guesses/1 or /guesses/1.json
  def update
    respond_to do |format|
      if @guess.update(guess_params)
        format.html { redirect_to @guess, notice: "Guess was successfully updated." }
        format.json { render :show, status: :ok, location: @guess }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guess.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guesses/1 or /guesses/1.json
  def destroy
    @guess.destroy
    respond_to do |format|
      format.html { redirect_to guesses_url, notice: "Guess was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guess
      @guess = Guess.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guess_params
      params.require(:guess).permit(:name)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new

    @person.guesses.build
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # Permitir los parametros de Guess
    def person_params
      params.require(:person).permit(:name, :age, {guess_ids: []}, {guesses_attributes: [:id, :name]})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/guesses/_form.html.erb
<%= form_with(model: guess, local: true) do |form| %>
  <% if guess.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guess.errors.count, "error") %> prohibited this guess from being saved:</h2>

      <ul>
      <% guess.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guesses/edit.html.erb
<h1>Editing Guess</h1>

<%= render 'form', guess: @guess %>

<%= link_to 'Show', @guess %> |
<%= link_to 'Back', guesses_path %>

app/views/guesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guesses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guesses.each do |guess| %>
      <tr>
        <td><%= guess.name %></td>
        <td><%= link_to 'Show', guess %></td>
        <td><%= link_to 'Edit', edit_guess_path(guess) %></td>
        <td><%= link_to 'Destroy', guess, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guess', new_guess_path %>

app/views/guesses/new.html.erb
<h1>New Guess</h1>

<%= render 'form', guess: @guess %>

<%= link_to 'Back', guesses_path %>

app/views/guesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guess.name %>
</p>

<%= link_to 'Edit', edit_guess_path(@guess) %> |
<%= link_to 'Back', guesses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cabalas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <!-- #Muestra en el formulario de people los guesses disponibles -->
  <div class="field">
    <%= form.label :guesses %>
    <%= form.collection_check_boxes(:guess_ids, Guess.all, :id, :name) do |g| %> 
      <%= g.label class: 'label-checkbox' do %>
        <%= g.check_box + g.text %>
      <% end %>
    <% end %>
  </div>

  <!-- #crear una nueva guess - Formulario utilizado por cocoon-->
  <div class="links">
    <%= link_to_add_association 'Agregar otra cabala', form, :guesses%>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_guess_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>    
    </div>
        <%= link_to_remove_association "remove task", f %>
</div>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <!-- #mostrar el campo guesses -->
      <th>Guesses</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.age %></td>
        <!--#Mostrar los guesses -->
        <!--#each para que muestre el verdadero nombre -->
        <td>
            <% person.guesses.each do |pg| %>
              <%= pg.name %>
            <% end %>
        </td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person.age %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>